### ISSUE TITLE
Get Involved, Contribute: Broken link

### ISSUE THREAD

**Issue by MikeDevs** [mage-os/mage-os-website#18]
The Github repository link at the bottom of [get-involved.md](https://github.com/mage-os/mage-os-website/blob/a9bf4ade34c897b5b30df097ef7fc9651264500e/src/pages/get-involved.md?plain=1#L37) is a 404. I am guessing it is either a private repo or a placeholder? Maybe just change it to "we will post the public repository when it becomes available".

**Comment by rhoerr** [comment]
Thanks for pointing that out! We'll get that fixed. I think the linked repository was removed; we don't have one for the eventual distribution/fork yet.

**Comment by rhoerr** [comment]
We've since republished the mageos-magento2 repository, so the link is working again. Thanks again!

https://github.com/mage-os/mageos-magento2
