### ISSUE TITLE
Add Twitter feed to homepage

### ISSUE THREAD

**Issue by rhoerr** [mage-os/mage-os-website#23]
We'd tentatively like to add a twitter feed from @mage_os to the homepage.

Vinai's progress to date is in https://github.com/mage-os/mage-os-website/tree/twitter-feed-embed . I need to pick it up from there.

**Comment by sprankhub** [comment]
Do we really want to do this? Probably, this means that Twitter sets cookies, which then require us to use a cookie banner and block the cookies / embed when the respective cookies have been blocked by the user. I'd keep it simple and just add static links / buttons to our social media sites.

**Comment by rhoerr** [comment]
Very good point. I'm not sure a social feed adds enough value to justify that. So far we haven't posted much other than updates already on the site. @Vinai, thoughts?

**Comment by rhoerr** [comment]
Closing out per discussion. We'll continue to post updates as appropriate.
